### ISSUE TITLE
add Aliyun OSS（Object Storage Service）

### ISSUE THREAD

**Issue by chenlb** [langfuse/langfuse-docs#1045]
https://help.aliyun.com/zh/oss/getting-started/oss-sdk-quick-start

**Comment by marcklingen** [comment]
Please follow this documentation on how to connect to Aliyun OSS via S3 api: [https://www.alibabacloud.com/help/en/oss/developer-reference/use-amazon-s3-sdks-to-access-oss](https://www.alibabacloud.com/help/en/oss/developer-reference/use-amazon-s3-sdks-to-access-oss)
