### ISSUE TITLE
Broken link to upgrade guides.

### ISSUE THREAD

**Issue by tobiasraabe** [langfuse/langfuse-docs#1104]
Hi,

thanks for the fantastic tool!

The link to the upgrade page is broken on https://langfuse.com/self-hosting/v2. The banner reads:

> This guide covers Langfuse v2. For Langfuse v3, see the [v3 documentation](https://langfuse.com/self-hosting). Langfuse v2 receives security updates until end of Q1 2025. If you have any questions while upgrading, please refer to the [v3 upgrade guide](https://langfuse.com/self-hosting/upgrade-v2-to-v3) or open a thread on [GitHub Discussions](https://langfuse.com/gh-support).

I guess the second link should be https://langfuse.com/self-hosting/upgrade-guides/upgrade-v2-to-v3.

**Comment by marcklingen** [comment]
thanks for sharing, fixed it
