### ISSUE TITLE
Found broken `/guides/cookbook/langfuse_prompt_with_langchain` link. Please fix!

### ISSUE THREAD

**Issue by Akki-bit-star** [langfuse/langfuse-docs#428]

**Comment by marcklingen** [comment]
thanks for reporting, where did you get this link? I could not find it across our docs/blog/changelog

correct link: https://langfuse.com/guides/cookbook/prompt_management_langchain

**Comment by marcklingen** [comment]
https://github.com/langfuse/langfuse-docs/commit/d9ddc832ac44e260ee574ea42072564e54d56d32
