### ISSUE TITLE
Found broken `/docs/integrations/sdk#1-backend-tracing` link. Please fix!

### ISSUE THREAD

**Issue by brodao2** [langfuse/langfuse-docs#553]
Many information pages is broken link.
![image](https://github.com/langfuse/langfuse-docs/assets/114854608/ecb91e97-a16b-4111-a6a8-831429dfaa24)

**Comment by marcklingen** [comment]
thank you!

fixed here: https://github.com/langfuse/langfuse/commit/e5261ac73da85ef564012f279b25d132bd90fc04
