### ISSUE TITLE
Found broken `/docs/evals` link. Please fix!

### ISSUE THREAD

**Issue by himansrivastava** [langfuse/langfuse-docs#630]
It is redirected from here:
![image](https://github.com/langfuse/langfuse-docs/assets/10616041/6398ba6b-c129-4075-98c4-070656563efb)

**Comment by marcklingen** [comment]
thanks, fixed in https://github.com/langfuse/langfuse/commit/4041550d5e4a2cd3b84a324874b8f12eadf8af86
