### ISSUE TITLE
Feedback for “I have setup Langfuse, but I do not see prompt name and its version in traces and generations. How to solve this?”

### ISSUE THREAD

**Issue by ksundarraj-c-rpx** [langfuse/langfuse-docs#760]
“I have setup Langfuse, but I do not see prompt name and its version in traces and generations. How to solve this?”

**Comment by marcklingen** [comment]
You can find more information on this here: https://langfuse.com/docs/prompts/get-started#link-with-langfuse-tracing-optional

Thanks for the feedback, I added a new FAQ page in https://github.com/langfuse/langfuse-docs/commit/b48bb712113c859a369f8544928d8c5b21896304
