### ISSUE TITLE
Does langfuse trace parallel api calls? I tried a sample with parallel call but it didn't traced. 

### ISSUE THREAD

**Issue by ksundarraj-c-rpx** [langfuse/langfuse-docs#763]
I tried a sample with parallel call but it didn't traced. I have called llm model by parallel calls using pandarallel but it has not been traced in the UI. But when i applied in a sequence one by one it got traced.

**Comment by marcklingen** [comment]
Can you open a thread here with more context? https://github.com/orgs/langfuse/discussions/categories/support
