### ISSUE TITLE
in feedback.ts file Implement Retry Logic for Slack Webhook Calls

### ISSUE THREAD

**Issue by wenayy** [langfuse/langfuse-docs#847]
The current implementation of the webhook handler sends feedback data to the Slack webhook using a simple fetch request. While this works under normal circumstances, it lacks resilience in the face of temporary issues such as network instability, timeouts, or Slack service outages. If the webhook call fails due to any temporary issue (e.g., network errors, rate-limiting by Slack, server unavailability), the request will fail permanently without retries, resulting in a poor user experience.

Objective: We should implement a retry mechanism that will attempt to resend the feedback data to Slack a certain number of times before giving up. This will help in ensuring that the request doesn't fail immediately due to temporary issues, improving the robustness of the system.

**Comment by marcklingen** [comment]
sounds good, open for contributions on this. alternatively, you could also handle the error state and display an error to try again

**Comment by wenayy** [comment]
assign me this i will try to work on each aspect

**Comment by marcklingen** [comment]
closing as stale and as this does not really matter that much, have not observed any issues related to this
