### ISSUE TITLE
Github discussions on https://langfuse.com/docs/prompts/get-started breaks in mobile view

### ISSUE THREAD

**Issue by sarthak-kumar-shailendra** [langfuse/langfuse-docs#886]
Github discussions on https://langfuse.com/docs/prompts/get-started breaks in mobile view.

<img width="308" alt="Screenshot 2024-10-23 at 12 08 43 AM" src="https://github.com/user-attachments/assets/cd1375fe-a066-43f5-b6a5-0af83eeb1bf1">

**Comment by marcklingen** [comment]
thanks for sharing, I think wrapping this correctly would be preferred. Are you interested in contributing to this?

**Comment by marcklingen** [comment]
fixed in https://github.com/langfuse/langfuse-docs/pull/887
